server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:cardsdb
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  h2:
    console:
      enabled: true
  jpa:    
    hibernate:
      ddl-auto: update
    show-sql: true
